<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "*": {-->
<!--            "registrationPopup": {}-->
<!--        }-->
<!--    }-->
<!--</script>-->

<div id="modal-content">
    <?php  $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Customer::form/register.phtml")->toHtml(); ?>

</div>

<button id="example-modal-button" data-mage-init='{"registrationPopup": {"target": "#modal-content"}}'>
    Registration for dealer
</button>

