<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="content-wrapper">
    <h1>
        <span>Your request has been successfully completed</span>
    </h1>
    <?php if ($block->getcustomText()): ?>
        <h3>
            <?= /* @escapeNotVerified */
            $block->getcustomText(); ?>
        </h3>
    <?php endif; ?>
    <a href="<?= $block->getUrl('test_module/demonstration/indexjson') ?>">Link to JSON controller</a>
</div>
