<?php /** @var Alex\RequestSample\Block\Requests $block */ ?>
<table>
    <tr>
        <th><?php echo __('Date'); ?></th>
        <th><?php echo __('Request'); ?></th>
        <th><?php echo __('Product'); ?></th>
        <th><?php echo __('Status'); ?></th>
    </tr>

    <?php foreach($block->getMySampleRequests() as $sampleRequest): ?>
        <tr>
            <td><?php echo $block->escapeHtml($sampleRequest->getCreatedAt()) ?></td>
            <td><?php echo $block->escapeHtml($sampleRequest->getRequest()) ?></td>
            <td><?php echo $block->escapeHtml($sampleRequest->getProductName()) ?></td>
            <td><?php echo $block->escapeHtml($sampleRequest->getStatus()) ?></td>
        </tr>
    <?php endforeach; ?>
</table>
