<?php /** @var $block \Overdose\LessonOne\Block\Overdose */ ?>
<?php /** @var $viewModel \Overdose\LessonOne\ViewModel\One */
$viewModel = $block->getData('viewModel');
?>


<h1>Hello, World!</h1>
<p>This is text from homepage.phtml in overdose_index_index.xml</p>

<p> <?= $block->doSomethingImportant() ?> </p>

<p> <?= $viewModel->iAmViewModel() ?> </p>

<!-- Add HTML Form with Input for Friend's ID and Display Results -->
<form method="post" action="?friend=getFriendInfo">
    <label for="friendId">Enter Friend's ID:</label>
    <input type="number" id="friendId" name="friendId" min="0" size="4" pattern="\d+" required>
    <br>
    <small>Only numbers allowed</small><br><br>
    <button type="submit">Get friend's name and age</button>
</form>

<!-- Friends form generator -->
<form method="post" action="?friend=generateFriends">
    <label for="friendCount">Number of Friends:</label>
    <input type="number" id="friendCount" name="friendCount" placeholder="1-100">
    <button type="submit">Generate Friends</button>
</form>


